"""organizacao empresas unidades colaboradores e vinculos

Revision ID: 0587408f5e7f
Revises: e034aeb50f33
Create Date: 2026-08-11 19:29:25.365772

Cria a organização da seção 8.2: empresas, unidades, colaboradores, papéis com
vigência (ADR-0013), chaves PIX versionadas, contas bancárias e os vínculos
consultor-líder.

Documento e PIX ficam em par cifrado + hash de busca (ADR-0012). O hash é único
em `collaborators.document_hash`, o que garante a deduplicação exigida em 8.7.

Impacto financeiro: indireto e relevante — papel vigente e líder na data
determinam quem recebe comissão a partir da F4. Nenhum valor é calculado aqui.
Reversível: sim, enquanto não houver proposta ou lançamento apontando para estes
cadastros.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.db.types.utc_datetime import UtcDateTime  # noqa: F401


revision: str = '0587408f5e7f'
down_revision: str | None = 'e034aeb50f33'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_encrypted', sa.String(length=255), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('document_hash', name=op.f('uq_companies_document_hash'))
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('bank_code', sa.String(length=5), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('branch', sa.String(length=10), nullable=False),
    sa.Column('account_encrypted', sa.String(length=255), nullable=False),
    sa.Column('account_masked', sa.String(length=30), nullable=False),
    sa.Column('account_type', sa.String(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_bank_accounts_company_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts'))
    )
    op.create_index('ix_bank_accounts_owner', 'bank_accounts', ['owner_type', 'owner_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_units_company_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('company_id', 'code', name='uq_units_company_id_code')
    )
    op.create_table('collaborators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('document_encrypted', sa.String(length=255), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=4), nullable=False),
    sa.Column('tax_regime', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_on', sa.Date(), nullable=True),
    sa.Column('deactivation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_collaborators_company_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_collaborators_unit_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collaborators_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaborators')),
    sa.UniqueConstraint('document_hash', name=op.f('uq_collaborators_document_hash')),
    sa.UniqueConstraint('user_id', name=op.f('uq_collaborators_user_id'))
    )
    op.create_index('ix_collaborators_company_id_is_active', 'collaborators', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_collaborators_full_name', 'collaborators', ['full_name'], unique=False)
    op.create_index('ix_collaborators_unit_id_is_active', 'collaborators', ['unit_id', 'is_active'], unique=False)
    op.create_table('collaborator_payment_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collaborator_id', sa.BigInteger(), nullable=False),
    sa.Column('key_type', sa.String(length=12), nullable=False),
    sa.Column('key_encrypted', sa.String(length=512), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_masked', sa.String(length=60), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], name=op.f('fk_collaborator_payment_keys_collaborator_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaborator_payment_keys'))
    )
    op.create_index('ix_collaborator_payment_keys_collaborator_id_valid_from', 'collaborator_payment_keys', ['collaborator_id', 'valid_from'], unique=False)
    op.create_table('collaborator_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collaborator_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], name=op.f('fk_collaborator_roles_collaborator_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaborator_roles'))
    )
    op.create_index('ix_collaborator_roles_collaborator_id_role_valid_from', 'collaborator_roles', ['collaborator_id', 'role', 'valid_from'], unique=False)
    op.create_index('ix_collaborator_roles_role_valid_from', 'collaborator_roles', ['role', 'valid_from'], unique=False)
    op.create_table('team_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consultant_id', sa.BigInteger(), nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('closing_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', UtcDateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['consultant_id'], ['collaborators.id'], name=op.f('fk_team_assignments_consultant_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leader_id'], ['collaborators.id'], name=op.f('fk_team_assignments_leader_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_assignments'))
    )
    op.create_index('ix_team_assignments_consultant_id_type_start_date', 'team_assignments', ['consultant_id', 'assignment_type', 'start_date'], unique=False)
    op.create_index('ix_team_assignments_leader_id_start_date', 'team_assignments', ['leader_id', 'start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Sem `op.drop_index`: o autogenerate emite o drop dos índices antes do drop
    # das tabelas, e o MySQL recusa remover índice que sustenta foreign key
    # (erro 1553). `drop_table` já remove os índices da própria tabela.
    # Ordem das folhas para as raízes, respeitando as FKs.
    op.drop_table('team_assignments')
    op.drop_table('collaborator_roles')
    op.drop_table('collaborator_payment_keys')
    op.drop_table('collaborators')
    op.drop_table('bank_accounts')
    op.drop_table('units')
    op.drop_table('companies')
