"""aprovacao de propostas e comprovantes

Revision ID: 2068e9347337
Revises: 594f1d7d78b2
Create Date: 2026-08-12 14:59:51.103058

Fluxo cadastro → financeiro (seções 7.4 e 13): a finalização/cobrança monta a
proposta, anexa o comprovante do pagamento do cliente e envia; o financeiro
aprova ou devolve com motivo. `approval_status` é dimensão separada do status
financeiro — rejeitada-e-paga não existe.

`proposal_attachments` guarda os metadados e o sha256 do comprovante; o arquivo
mora no object storage.

Backfill: propostas existentes viram APPROVED — entraram antes do fluxo existir
e já valem para o financeiro; puni-las com rascunho retroativo travaria dado bom.

Impacto financeiro: indireto e alto — a partir daqui, só proposta aprovada deve
contar para recebimento e comissão (aplicado na F3/F4). Nenhum valor é alterado.
Reversível: sim; o downgrade perde apenas o estado do fluxo e os metadados de
anexo, nunca valor financeiro.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.db.types.utc_datetime import UtcDateTime  # noqa: F401


revision: str = '2068e9347337'
down_revision: str | None = '594f1d7d78b2'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_proposal_attachments_proposal_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_proposal_attachments_storage_key'))
    )
    op.create_index('ix_proposal_attachments_proposal_id_uploaded_at', 'proposal_attachments', ['proposal_id', 'uploaded_at'], unique=False)
    # server_default faz o backfill das linhas existentes como APPROVED; o
    # default é removido em seguida — proposta nova recebe DRAFT da aplicação
    op.add_column(
        'proposals',
        sa.Column('approval_status', sa.String(length=12), nullable=False,
                  server_default='APPROVED'),
    )
    op.alter_column('proposals', 'approval_status', existing_type=sa.String(length=12),
                    server_default=None)
    op.add_column('proposals', sa.Column('submitted_at', UtcDateTime(), nullable=True))
    op.add_column('proposals', sa.Column('submitted_by', sa.BigInteger(), nullable=True))
    op.add_column('proposals', sa.Column('decided_at', UtcDateTime(), nullable=True))
    op.add_column('proposals', sa.Column('decided_by', sa.BigInteger(), nullable=True))
    op.add_column('proposals', sa.Column('rejection_reason', sa.String(length=255), nullable=True))
    op.create_index('ix_proposals_approval_status_submitted_at', 'proposals', ['approval_status', 'submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_proposals_approval_status_submitted_at', table_name='proposals')
    op.drop_column('proposals', 'rejection_reason')
    op.drop_column('proposals', 'decided_by')
    op.drop_column('proposals', 'decided_at')
    op.drop_column('proposals', 'submitted_by')
    op.drop_column('proposals', 'submitted_at')
    op.drop_column('proposals', 'approval_status')
    # sem drop_index em proposal_attachments: o índice sustenta a FK de
    # proposal_id e o MySQL recusaria (1553); drop_table já o remove
    op.drop_table('proposal_attachments')
