"""importador legado staging e rastreabilidade

Revision ID: 594f1d7d78b2
Revises: b3c1d9a47f52
Create Date: 2026-08-12 13:39:27.184083

Cria a infraestrutura do importador legado (seção 18): `legacy_import_runs`, uma
linha por execução, e `legacy_import_issues`, a fila de exceção com os registros
que o importador se recusa a resolver adivinhando.

Acrescenta `legacy_source`/`legacy_id` a `collaborators` e `proposals`. O par é
único: o importador pode rodar quantas vezes for preciso sem duplicar cadastro.
Nulo em registro nascido na v2.

Impacto financeiro: nenhum nesta migração — só colunas de rastreabilidade e
tabelas de relatório. Na F2 o importador roda em dry-run e não escreve em tabela
canônica; a carga real é da F7.
Reversível: sim. As colunas novas são nulas e nenhuma regra depende delas ainda.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.db.types.utc_datetime import UtcDateTime  # noqa: F401


revision: str = '594f1d7d78b2'
down_revision: str | None = 'b3c1d9a47f52'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_import_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('finished_at', UtcDateTime(), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('triggered_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_import_runs'))
    )
    op.create_table('legacy_import_issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_table', sa.String(length=40), nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['legacy_import_runs.id'], name=op.f('fk_legacy_import_issues_run_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_import_issues'))
    )
    op.create_index('ix_legacy_import_issues_run_id_severity', 'legacy_import_issues', ['run_id', 'severity'], unique=False)
    op.create_index('ix_legacy_import_issues_source_legacy_id', 'legacy_import_issues', ['source_table', 'legacy_id'], unique=False)
    op.add_column('collaborators', sa.Column('legacy_source', sa.String(length=40), nullable=True))
    op.add_column('collaborators', sa.Column('legacy_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_collaborators_legacy', 'collaborators', ['legacy_source', 'legacy_id'])
    op.add_column('proposals', sa.Column('legacy_source', sa.String(length=40), nullable=True))
    op.add_column('proposals', sa.Column('legacy_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_proposals_legacy', 'proposals', ['legacy_source', 'legacy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('uq_proposals_legacy', 'proposals', type_='unique')
    op.drop_column('proposals', 'legacy_id')
    op.drop_column('proposals', 'legacy_source')
    op.drop_constraint('uq_collaborators_legacy', 'collaborators', type_='unique')
    op.drop_column('collaborators', 'legacy_id')
    op.drop_column('collaborators', 'legacy_source')
    # Sem `op.drop_index`: `ix_legacy_import_issues_run_id_severity` sustenta a
    # foreign key de `run_id`, e o MySQL recusa removê-lo antes da tabela (1553).
    # `drop_table` já leva os índices da própria tabela.
    op.drop_table('legacy_import_issues')
    op.drop_table('legacy_import_runs')
