"""identidade auditoria e outbox

Revision ID: e034aeb50f33
Revises: 
Create Date: 2026-08-11 16:50:08.829093

Cria a base de identidade (users, roles, permissions e associações), sessões e
tentativas de login (ADR-0003), a trilha de auditoria append-only e o outbox.

Impacto financeiro: nenhum — não há tabela de valor nesta revisão.
Reversível: sim. Em ambiente com dado real, exportar `audit_events` antes do
downgrade: a trilha está sujeita a retenção legal (seção 13.3).
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.platform.db.types.utc_datetime import UtcDateTime  # noqa: F401


revision: str = 'e034aeb50f33'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('aggregate_type', sa.String(length=40), nullable=True),
    sa.Column('aggregate_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_actor_occurred_at', 'audit_events', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_aggregate', 'audit_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_audit_events_correlation_id', 'audit_events', ['correlation_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip_hash', sa.String(length=32), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('attempted_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_email_attempted_at', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('ix_login_attempts_ip_hash_attempted_at', 'login_attempts', ['ip_hash', 'attempted_at'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_type', sa.String(length=40), nullable=True),
    sa.Column('aggregate_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('available_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('processed_at', UtcDateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_events_processed_at_available_at', 'outbox_events', ['processed_at', 'available_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', UtcDateTime(), nullable=True),
    sa.Column('created_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('issued_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('expires_at', UtcDateTime(), nullable=False),
    sa.Column('last_used_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('rotated_at', UtcDateTime(), nullable=True),
    sa.Column('revoked_at', UtcDateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=60), nullable=True),
    sa.Column('ip_hash', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index('ix_sessions_token_hash_expires_at', 'sessions', ['token_hash', 'expires_at'], unique=False)
    op.create_index('ix_sessions_user_id_revoked_at', 'sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_at', UtcDateTime(), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_user_roles_granted_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Sem `op.drop_index` aqui: o autogenerate emite o drop dos índices antes do
    # drop das tabelas, e o MySQL recusa remover um índice que ainda sustenta uma
    # foreign key (erro 1553). `drop_table` já remove os índices da tabela.
    # A ordem abaixo respeita as dependências de FK, das folhas para as raízes.
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('outbox_events')
    op.drop_table('login_attempts')
    op.drop_table('audit_events')
