import { Alert, Badge, Button, Card, Group, Modal, SimpleGrid, Stack, Table, Tabs, Text, TextInput, Title } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { IconCopy, IconPlayerPlay } from '@tabler/icons-react';
import { useState } from 'react';

import { useAuth } from '@/app/providers/AuthProvider';
import { CommissionStrategyConfigModal } from '@/features/commission-rules/components/CommissionStrategyConfigModal';
import { useActivateCommissionStrategyConfig } from '@/features/commission-rules/mutations/useCommissionStrategyConfigs';
import { useCommissionStrategyConfigs } from '@/features/commission-rules/queries/useCommissionStrategyConfigs';
import { EstadoDaLista } from '@/shared/components/EstadoDaLista';
import { decimalParaPercentual } from '@/shared/formatters/percent-mask';
import type { CommissionStrategy, CommissionStrategyConfig } from '@/shared/types/commissions';

const dinheiro = (valor: unknown) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 2 }).format(Number(valor));
const pct = (valor: unknown) => `${decimalParaPercentual(String(valor ?? '0'))}%`;
const titulo: Record<CommissionStrategy, string> = { SCALED_CONSULTANT: 'Consultor escalonado', COMMERCIAL_LEADER: 'Líder comercial', GENERAL_MEI_LEADER: 'Líder MEI geral', FINALIZER: 'Finalização', FINALIZATION_LEADER: 'Líder de Finalização' };

function Vigencia({ config }: { config: CommissionStrategyConfig }) {
  return <Group gap="xs"><Badge color={config.status === 'ACTIVE' ? 'positivo' : 'yellow'} variant="light">{config.status === 'ACTIVE' ? 'Ativa' : 'Rascunho'}</Badge><Text size="xs" c="dimmed">v{config.version} · desde {config.valid_from.split('-').reverse().join('/')}</Text></Group>;
}

function Conteudo({ item }: { item: CommissionStrategyConfig }) {
  const c = item.config;
  if (item.strategy === 'SCALED_CONSULTANT') return <Table withTableBorder striped><Table.Thead><Table.Tr><Table.Th>Produção</Table.Th><Table.Th ta="right">TPS ≥ 35%</Table.Th><Table.Th ta="right">TPS 30–34,99%</Table.Th><Table.Th ta="right">TPS 25–29,99%</Table.Th><Table.Th ta="right">TPS &lt; 25%</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{(c.production_ranges ?? []).map((faixa) => <Table.Tr key={faixa.min}><Table.Td>{dinheiro(faixa.min)} até {faixa.max === null ? 'sem limite' : dinheiro(faixa.max)}</Table.Td>{faixa.percentages.map((valor, i) => <Table.Td key={i} ta="right">{pct(valor)}</Table.Td>)}</Table.Tr>)}</Table.Tbody></Table>;
  if (item.strategy === 'COMMERCIAL_LEADER') return <Table><Table.Thead><Table.Tr><Table.Th>Regime e TPS</Table.Th><Table.Th ta="right">Comissão</Table.Th></Table.Tr></Table.Thead><Table.Tbody><Table.Tr><Table.Td>MEI com TPS ≥ {pct(c.mei_min_tps)}</Table.Td><Table.Td ta="right">{pct(c.mei_percentage)}</Table.Td></Table.Tr><Table.Tr><Table.Td>MEI abaixo do mínimo</Table.Td><Table.Td ta="right">0%</Table.Td></Table.Tr><Table.Tr><Table.Td>CLT em qualquer TPS</Table.Td><Table.Td ta="right">{pct(c.clt_percentage)}</Table.Td></Table.Tr></Table.Tbody></Table>;
  if (item.strategy === 'GENERAL_MEI_LEADER') return <Stack gap="xs"><Text size="sm">Base inicial: <strong>{pct(c.base_percentage)} da produção proporcional</strong>.</Text><Table><Table.Thead><Table.Tr><Table.Th>Produção</Table.Th><Table.Th ta="right">Comissão</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{(c.tiers ?? []).map((faixa) => <Table.Tr key={faixa.min}><Table.Td>{dinheiro(faixa.min)} até {dinheiro(faixa.max)}</Table.Td><Table.Td ta="right">{pct(faixa.percentage)}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Stack>;
  if (item.strategy === 'FINALIZER') return <Stack gap="xs"><Text size="sm">Abaixo de {dinheiro(c.threshold_amount)}: <strong>R$ 0,00</strong></Text><Text size="sm">A partir do limite: <strong>{dinheiro(c.fixed_amount)} + {pct(c.excess_percentage)}</strong> sobre o excedente.</Text><Text size="xs" c="dimmed">Bônus manual é lançamento separado.</Text></Stack>;
  return <Stack gap="xs"><Text size="sm">Comissão MEI: <strong>{pct(c.mei_percentage)}</strong></Text><Text size="sm">Comissão CLT: <strong>{pct(c.clt_percentage)}</strong></Text><Text size="xs" c="dimmed">Desconto aprovado reduz o líquido, nunca abaixo de zero.</Text></Stack>;
}

export function CommissionRulesCatalog() {
  const { pode } = useAuth(); const consulta = useCommissionStrategyConfigs(); const ativar = useActivateCommissionStrategyConfig();
  const [editor, setEditor] = useState<CommissionStrategyConfig | null>(null); const [paraAtivar, setParaAtivar] = useState<CommissionStrategyConfig | null>(null); const [motivo, setMotivo] = useState('');
  const porEstrategia = (strategy: CommissionStrategy) => (consulta.data ?? []).filter((item) => item.strategy === strategy);
  const atual = (strategy: CommissionStrategy) => porEstrategia(strategy).find((item) => item.status === 'ACTIVE') ?? porEstrategia(strategy)[0];
  const card = (strategy: CommissionStrategy) => { const item = atual(strategy); if (!item) return null; const drafts = porEstrategia(strategy).filter((x) => x.status === 'DRAFT'); return <Card withBorder key={strategy}><Stack gap="xs"><Group justify="space-between"><Title order={3} size="h5">{titulo[strategy]}</Title><Vigencia config={item} /></Group><Conteudo item={item} /><Group justify="space-between" mt="xs"><Text size="xs" c="dimmed">{drafts.length ? `${drafts.length} rascunho(s) aguardando ativação` : 'Sem correções pendentes'}</Text>{pode('commission_rules:write') && <Button size="xs" variant="default" leftSection={<IconCopy size={14} />} onClick={() => setEditor(item)}>Corrigir em nova versão</Button>}</Group>{drafts.map((draft) => <Group key={draft.id} justify="space-between" p="xs" bg="yellow.0"><Vigencia config={draft} />{pode('commission_rules:activate') && <Button size="xs" color="positivo" leftSection={<IconPlayerPlay size={14} />} onClick={() => setParaAtivar(draft)}>Ativar</Button>}</Group>)}</Stack></Card>; };
  const confirmar = () => paraAtivar && ativar.mutate({ id: paraAtivar.id, reason: motivo }, { onSuccess: () => { notifications.show({ color: 'positivo', title: 'Versão ativada', message: `A versão ${paraAtivar.version} foi programada.` }); setParaAtivar(null); setMotivo(''); }, onError: (erro) => notifications.show({ color: 'red', title: erro.problem.title, message: erro.problem.detail }) });

  return <Card withBorder radius="md" padding="lg"><Stack><div><Title order={3} size="h4">Demais regras configuráveis</Title><Text size="sm" c="dimmed">Cada grupo possui histórico, vigência e editor próprios.</Text></div><Alert color="blue" title="Como corrigir uma faixa?">Use “Corrigir em nova versão”, ajuste os valores e informe a vigência. Depois confira e ative o rascunho; a configuração anterior será preservada.</Alert><EstadoDaLista carregando={consulta.isPending} erro={consulta.error ?? null} vazio={(consulta.data ?? []).length === 0} mensagemVazio="Nenhuma estratégia configurada."><Tabs defaultValue="scaled" keepMounted={false}><Tabs.List><Tabs.Tab value="scaled">MEI Escalonado</Tabs.Tab><Tabs.Tab value="leaders">Lideranças</Tabs.Tab><Tabs.Tab value="finalization">Finalização e BKO</Tabs.Tab></Tabs.List><Tabs.Panel value="scaled" pt="md">{card('SCALED_CONSULTANT')}</Tabs.Panel><Tabs.Panel value="leaders" pt="md"><SimpleGrid cols={{ base: 1, lg: 2 }}>{card('COMMERCIAL_LEADER')}{card('GENERAL_MEI_LEADER')}</SimpleGrid></Tabs.Panel><Tabs.Panel value="finalization" pt="md"><SimpleGrid cols={{ base: 1, lg: 3 }}>{card('FINALIZER')}{card('FINALIZATION_LEADER')}<Card withBorder><Stack gap="xs"><Group justify="space-between"><Title order={3} size="h5">BKO</Title><Badge variant="light">Manual</Badge></Group><Text size="sm">Não possui percentual automático.</Text><Text size="sm">BKO MEI recebe lançamento manual positivo; BKO CLT não recebe.</Text></Stack></Card></SimpleGrid></Tabs.Panel></Tabs></EstadoDaLista><CommissionStrategyConfigModal opened={editor !== null} source={editor} onClose={() => setEditor(null)} /><Modal opened={paraAtivar !== null} onClose={() => setParaAtivar(null)} title="Ativar correção" centered><Stack><Text size="sm">A versão vigente será encerrada no dia anterior. O histórico calculado não será alterado.</Text><TextInput label="Motivo da ativação" value={motivo} onChange={(e) => setMotivo(e.currentTarget.value)} required /><Group justify="flex-end"><Button variant="default" onClick={() => setParaAtivar(null)}>Cancelar</Button><Button color="positivo" disabled={motivo.trim().length < 3} loading={ativar.isPending} onClick={confirmar}>Confirmar ativação</Button></Group></Stack></Modal></Stack></Card>;
}
