import { ActionIcon, Alert, Badge, Button, Divider, Grid, Group, Modal, Select, Stack, Table, TextInput } from '@mantine/core';
import { IconPencil, IconPlayerPlay, IconTrash } from '@tabler/icons-react';
import { useEffect, useState } from 'react';
import { useBankAccounts, useSaveBankAccount, useSetBankAccountStatus, type BankAccount } from '@/features/collaborators/queries/useBankAccounts';
import type { Collaborator } from '@/shared/types/organization';

const EMPTY = { bank_code: '', bank_name: '', branch: '', account_number: '', account_type: 'CORRENTE' };
export function CollaboratorBankAccountsModal({ collaborator, onClose }: { collaborator: Collaborator | null; onClose: () => void }) {
  const id = collaborator?.id ?? 0; const query = useBankAccounts(collaborator?.id ?? null); const save = useSaveBankAccount(id); const status = useSetBankAccountStatus(id); const [editing, setEditing] = useState<BankAccount | null>(null); const [form, setForm] = useState(EMPTY);
  useEffect(() => { setEditing(null); setForm(EMPTY); }, [collaborator]);
  if (!collaborator) return null;
  const choose = (item: BankAccount) => { setEditing(item); setForm({ bank_code: item.bank_code, bank_name: item.bank_name, branch: item.branch, account_number: '', account_type: item.account_type }); };
  return <Modal opened onClose={onClose} title={`Contas bancárias — ${collaborator.full_name}`} size="lg" centered><Stack>
    {(query.error ?? save.error ?? status.error) && <Alert color="red">{(query.error ?? save.error ?? status.error)?.problem.detail}</Alert>}
    <Table striped><Table.Thead><Table.Tr><Table.Th>Banco</Table.Th><Table.Th>Agência/conta</Table.Th><Table.Th>Tipo</Table.Th><Table.Th>Situação</Table.Th><Table.Th>Ações</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{(query.data ?? []).map((item) => <Table.Tr key={item.id}><Table.Td>{item.bank_code} — {item.bank_name}</Table.Td><Table.Td>{item.branch} / {item.account_masked}</Table.Td><Table.Td>{item.account_type}</Table.Td><Table.Td><Badge color={item.is_active ? 'positivo' : 'gray'}>{item.is_active ? 'Ativa' : 'Inativa'}</Badge></Table.Td><Table.Td><Group gap={4}><ActionIcon variant="subtle" onClick={() => choose(item)}><IconPencil size={16} /></ActionIcon><ActionIcon variant="subtle" color={item.is_active ? 'red' : 'positivo'} onClick={() => status.mutate({ id: item.id, is_active: !item.is_active })}>{item.is_active ? <IconTrash size={16} /> : <IconPlayerPlay size={16} />}</ActionIcon></Group></Table.Td></Table.Tr>)}</Table.Tbody></Table>
    <Divider label={editing ? 'Editar conta' : 'Nova conta'} labelPosition="left" /><Grid><Grid.Col span={3}><TextInput label="Código do banco" value={form.bank_code} onChange={(e) => setForm({ ...form, bank_code: e.currentTarget.value })} /></Grid.Col><Grid.Col span={9}><TextInput label="Banco" value={form.bank_name} onChange={(e) => setForm({ ...form, bank_name: e.currentTarget.value })} /></Grid.Col><Grid.Col span={4}><TextInput label="Agência" value={form.branch} onChange={(e) => setForm({ ...form, branch: e.currentTarget.value })} /></Grid.Col><Grid.Col span={4}><TextInput label={editing ? 'Nova conta (opcional)' : 'Número da conta'} value={form.account_number} onChange={(e) => setForm({ ...form, account_number: e.currentTarget.value })} /></Grid.Col><Grid.Col span={4}><Select label="Tipo" data={['CORRENTE', 'POUPANCA', 'PAGAMENTO']} value={form.account_type} onChange={(v) => setForm({ ...form, account_type: v ?? 'CORRENTE' })} /></Grid.Col></Grid>
    <Group justify="space-between"><Button variant="default" onClick={onClose}>Fechar</Button><Group>{editing && <Button variant="subtle" onClick={() => { setEditing(null); setForm(EMPTY); }}>Cancelar edição</Button>}<Button loading={save.isPending} disabled={!form.bank_code || !form.bank_name || !form.branch || (!editing && !form.account_number)} onClick={() => save.mutate({ id: editing?.id, bank_code: form.bank_code, bank_name: form.bank_name, branch: form.branch, account_number: form.account_number || null, account_type: form.account_type }, { onSuccess: () => { setEditing(null); setForm(EMPTY); } })}>{editing ? 'Salvar conta' : 'Adicionar conta'}</Button></Group></Group>
  </Stack></Modal>;
}
